"""add api token expiry and records composite index

Revision ID: 7f7c07383cf9
Revises: 1f4a8c2e9d3b
Create Date: 2026-08-23 15:33:50.723165

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f7c07383cf9"
down_revision: str | None = "1f4a8c2e9d3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.add_column(sa.Column("expires_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_records_entity_deleted", ["entity_id", "deleted_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.drop_index("ix_records_entity_deleted")

    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_column("expires_at")

    # ### end Alembic commands ###
